language: objective-c
osx_image: xcode7.1
install:
  - brew update && brew install carthage
  - carthage bootstrap --no-use-binaries --platform ios
cache:
  directories:
    - Carthage/Build
notifications:
  flowdock: 43542f5ac151698f320ae1c4b95f9536
