language: objective-c
osx_image: xcode7.2
xcode_project: FestApp.xcodeproj
xcode_scheme: FestApp
xcode_sdk: iphonesimulator9.2
before_install:
  - brew update
  - brew install carthage || brew outdated carthage || brew upgrade carthage
install:
  - carthage bootstrap --no-use-binaries --platform ios
script:
  - xctool
cache:
  directories:
   - Carthage/Build
notifications:
  flowdock: 43542f5ac151698f320ae1c4b95f9536
